photosBundle\Entity\Uploads:
    type: entity
    table: null
    repositoryClass: photosBundle\Repository\UploadsRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        photos:
            type: string
            length: 255

    lifecycleCallbacks:
        prePersist: [ preUpload ]
        preUpdate: [ preUpload ]
        postPersist: [ upload ]
        postUpdate: [ upload ]
        postRemove: [ removeUpload ]
