<?php

namespace OrthoBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AdjonctionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdjonctionsRepository extends EntityRepository
{

    public function getComments()
    {
        $queryBuilder = $this->createQueryBuilder('adjonction');

        $queryBuilder->select('adjonction.commentairesAdj');

        return $queryBuilder->getQuery()->getResult();
        }
}
