<?php

namespace OrthoBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AdjonctionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdjonctionsRepository extends EntityRepository
{
    public function orderAdjonctionsByWeight()
    {
        $queryBuilder = $this->createQueryBuilder('adjonctions');

        $queryBuilder->leftJoin('adjonctions.poids', 'p')
            ->orderBy('p.poids', 'DESC')
            ->setMaxResults(10);

        return $queryBuilder;

    }
    public function getComments()
    {
        $queryBuilder = $this->createQueryBuilder('adjonction');

        // On sélectionne tout les id, ainsi que tout les commentaires
        $queryBuilder->select('adjonction.id', 'adjonction.nom', 'adjonction.commentaire', 'adjonction.famille', 'adjonction.image');
        return $queryBuilder->getQuery()->getResult();
    }
}
