<?php

namespace OrthoBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AdjonctionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdjonctionsRepository extends EntityRepository
{

    public function getComments()
    {
        $queryBuilder = $this->createQueryBuilder('adjonction');

        // On sélectionne tout les id, ainsi que tout les commentaires
        $queryBuilder->select('adjonction.idAdj', 'adjonction.titreAdj', 'adjonction.commentairesAdj', 'adjonction.familleAdj');

        return $queryBuilder->getQuery()->getResult();
    }
}
