<?php

namespace OrthoBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AppareillagesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AppareillagesRepository extends EntityRepository
{
    public function getAllOrderedByWeight(\OrthoBundle\Entity\Laboratoire $laboratoire)
    {
        
    }

    public function triParPoids()
    {
        $queryBuilder = $this->createQueryBuilder('u');

        $queryBuilder->leftJoin('u.poids', 'p')
                        ->orderBy('p.poids', 'DESC')
                        ->setMaxResults(10);

        return $queryBuilder;
    }

    public function getComments()
    {
        // Début du Query Builder
        $queryBuilder = $this->createQueryBuilder('appareillage');

        // On sélectionne tout les id, ainsi que tout les commentaires
        $queryBuilder->select('appareillage.id', 'appareillage.titreApp', 'appareillage.commentairesApp', 'appareillage.familleApp');

        // On retourne le résultat
        return $queryBuilder->getQuery()->getResult();
    }
}
