<?php

namespace OrthoBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AppareillagesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AppareillagesRepository extends EntityRepository
{
    public function getAllOrderedByWeight(\OrthoBundle\Entity\Laboratoire $laboratoire)
    {
        
    }

    public function triParPoids()
    {
        $queryBuilder = $this->createQueryBuilder('u');

        $queryBuilder->leftJoin('u.poids', 'p')
                        ->orderBy('p.poids', 'DESC');

        return $queryBuilder;
    }

    public function getnameandimage(){

        $queryBuilder = $this->createQueryBuilder('appareillages')
                            ->select('appareillages.titreApp', 'appareillages.imgApp')
                            ->where('appareillages.familleApp = :famille')
                            ->setParameter('famille', 'mob');

        return $queryBuilder->getQuery()->getResult();

    }


}
