<?php

namespace OrthoBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CabinetsdentairesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CabinetsdentairesRepository extends EntityRepository
{
    public function getActualUser()
    {
        $queryBuilder = $this->createQueryBuilder('user');
        
        $queryBuilder->leftJoin('user.fidLabo', 'laboratoire')
                    ->select('user', 'laboratoire')
                    ->where('user.id = :id')
                    ->setParameter('id', 1);

        return $queryBuilder->getQuery()->getResult();
    }

    public function getTotalCabinet()
    {
        $queryBuilder = $this->createQueryBuilder('cabinet')
            ->select('COUNT(cabinet.id)');

        return $queryBuilder->getQuery()->getResult();
    }
}
