<?php

namespace OrthoBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CabinetsdentairesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CabinetsdentairesRepository extends EntityRepository
{
    public function getActualUser()
    {
        $queryBuilder = $this->createQueryBuilder('user');
        
        $queryBuilder->leftJoin('user.fidLabo', 'laboratoire')
                    ->select('user', 'laboratoire')
                    ->where('user.id = :id')
                    ->setParameter('id', 2);
                    // TODO : Passer un paramètre sur la fonction pour trouver le cabinet qui est authentifié
        
        return $queryBuilder->getQuery()->getResult();
    }
}
