<?php

namespace OrthoBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CommandesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandesRepository extends EntityRepository
{
 
    public function getTotalCommandes()
    {
        $queryBuilder = $this->createQueryBuilder('commandes')
                            ->select('COUNT(commandes.id)');
        
        return $queryBuilder->getQuery()->getResult();
    }
}