liste_app:
    path:     /listeapp
    defaults: { _controller: "OrthoBundle:Appareillages:index" }
    methods:  GET

fiche_app:
    path:     /ficheapp/{id}
    defaults: { _controller: "OrthoBundle:Appareillage:show"}
    methods: [POST, GET]

crea_app:
    path:     /ajoutapp/
    defaults: { _controller: "OrthoBundle:Appareillage:new" }
    methods: [POST, GET]

edit_adj:
    path:     /{id}/editapp
    defaults: { _controller: "OrthoBundle:Appareillage:edit" }
    methods:  [GET, POST]

sup_app:
    path:   /supapp/
    defaults:   { _controller: "OrthoBundle:Appareillage:delete"}
    methods: [POST, GET]

