liste_app:
    path:     /listeapp
    defaults: { _controller: OrthoBundle:Appareillage:index }
    methods:  GET

fiche_app:
    path:     /{id}/ficheapp
    defaults: { _controller: OrthoBundle:Appareillage:show }
    methods:  GET

crea_app:
    path:     /creaapp
    defaults: { _controller: OrthoBundle:Appareillage:new }
    methods:  [GET, POST]

edit_app:
    path:     /{id}/editapp
    defaults: { _controller: OrthoBundle:Appareillage:edit }
    methods:  [GET, POST]

sup_app:
    path:     /{id}/supapp
    defaults: { _controller: OrthoBundle:Appareillage:delete }
    methods:  DELETE


