liste_cabinet:
    path:     /listecab
    defaults: { _controller: OrthoBundle:Cabinet:index }
    methods:  GET

fiche_cabinet:
    path:     /fichecabinet/{id}
    defaults: { _controller: OrthoBundle:Cabinet:show }
    methods: [POST, GET]

crea_cabinet:
    path:     /cabinet
    defaults: { _controller: OrthoBundle:Cabinet:new }
    methods: [POST, GET]

edit_cabinet:
    path:     /{id}/editcabinet
    defaults: { _controller: OrthoBundle:Cabinet:edit }
    methods:  [GET, POST]

sup_cabinet:
    path:   /supcabinet/
    defaults:    { _controller: OrthoBundle:Cabinet:delete }
    methods: [POST, GET]

