liste_user:
    path:     /liste/user
    defaults: { _controller: OrthoBundle:Usergestion:index }
    methods:  GET

fiche_user:
    path:     /fiche/user/{id}
    defaults: { _controller: OrthoBundle:Usergestion:show }
    methods: [POST, GET]

crea_user:
    path:     /ajouter/user
    defaults: { _controller: OrthoBundle:Usergestion:new }
    methods: [POST, GET]

edit_user:
    path:     /editer/user/{id}
    defaults: { _controller: OrthoBundle:Usergestion:edit }
    methods:  [GET, POST]

sup_user:
    path:   /{id}/supprimer/user
    defaults:    { _controller: OrthoBundle:Usergestion:delete }
    methods:  DELETE

