ortho_formulaire:
    path:     /formulaire
    defaults: { _controller: OrthoBundle:Formulaire:createFormulaire }
    methods: [POST, GET]

recap_formulaire:
    path:     /recap_formulaire/{id}
    defaults: { _controller: OrthoBundle:RecapFormulaire:showRecapFormulaire }
    methods: [POST, GET]

crea_cabinet:
    path:     /cabinet
    defaults: { _controller: OrthoBundle:Cabinet:create }
    methods: [POST, GET]

fiche_cabinet:
    path:     /fichecabinet/{id}
    defaults: { _controller: OrthoBundle:Cabinet:show }
    methods: [POST, GET]

crea_app:
    path:     /ajoutapp/
    defaults: { _controller: OrthoBundle:SuperAdmin:creationAppareillage }
    methods: [POST, GET]

recap_crea_app:
    path:    /recapapp/
    defaults: { _controller: OrthoBundle:SuperAdmin:recapAppareillage }
    methods: [POST, GET]

crea_adj:
    path:   /ajoutadj/
    defaults:    { _controller: OrthoBundle:SuperAdmin:creationAdjonction}
    methods: [POST,GET]

recap_crea_adj:
   path:    /recapadj/
   defaults:   { _controller: OrthoBundle:SuperAdmin:recapAdjonction}
   methods: [POST,GET]

crea_labo:
    path:     /laboratoire
    defaults: { _controller: OrthoBundle:Laboratoire:create }
    methods: [POST, GET]

fiche_labo:
    path:     /fichelaboratoire/{id}
    defaults: { _controller: OrthoBundle:Laboratoire:show }
    methods: [POST, GET]

recup_commandes:
    path:     /commandes
    defaults: { _controller: OrthoBundle:Commandes:show }
    methods: [POST, GET]

recup_user:
    path:     /utilisateurs
    defaults: { _controller: OrthoBundle:User:show }
