ortho_formulaire:
    path:     /formulaire
    defaults: { _controller: OrthoBundle:Formulaire:createFormulaire }
    methods: [POST, GET]

recap_formulaire:
    path:     /recap_formulaire/{id}
    defaults: { _controller: OrthoBundle:RecapFormulaire:showRecapFormulaire }
    methods: [POST, GET]

crea_cabinet:
    path:     /cabinet/
    defaults: { _controller: OrthoBundle:Cabinet:create }
    methods: [POST, GET]

fiche_cabinet:
    path:     /fichecabinet/{id}
    defaults: { _controller: OrthoBundle:Cabinet:show }
    methods: [POST, GET]
