ortho_formulaire:
    path:     /formulaire
    defaults: { _controller: OrthoBundle:Formulaire:createFormulaire }
    methods: [POST, GET]

recap_formulaire:
    path:     /recap_formulaire/{id}
    defaults: { _controller: OrthoBundle:RecapFormulaire:showRecapFormulaire }
    methods: [POST, GET]

recup_commandes:
    path:     /commandes
    defaults: { _controller: OrthoBundle:Commandes:show }
    methods: [POST, GET]

recup_user:
    path:     /utilisateurs
    defaults: { _controller: OrthoBundle:User:show }

