ortho_homepage:
    path:     /
    defaults: { _controller: OrthoBundle:Default:index }

ortho_formulaire:
    path:     /formulaire
    defaults: { _controller: OrthoBundle:Default:create }
    methods: [POST, GET]

envoi_bdd:
    path:     /envoiok
    defaults: { _controller: OrthoBundle:Default:envoi }
    methods: [POST, GET]