ortho_formulaire:
    path:     /formulaire
    defaults: { _controller: OrthoBundle:Default:create }
    methods: [POST, GET]

recap_formulaire:
    path:     /recap_formulaire
    defaults: { _controller: OrthoBundle:Default:show }
    methods: [POST, GET]

photos_uploads:
    resource: "@OrthoBundle/Resources/config/routing/uploads.yml"
    prefix:   /uploads

photos_homepage:
    path:     /truc
    defaults: { _controller: OrthoBundle:Default:index }

