ortho_formulaire:
    path:     /formulaire
    defaults: { _controller: OrthoBundle:Formulaire:createFormulaire }
    methods: [POST, GET]

recap_formulaire:
    path:     /recap_formulaire/{id}
    defaults: { _controller: OrthoBundle:RecapFormulaire:showRecapFormulaire }
    methods: [POST, GET]
