ortho_formulaire:
    path:     /formulaire
    defaults: { _controller: OrthoBundle:Default:create }
    methods: [POST, GET]

recap_formulaire:
    path:     /recap_formulaire
    defaults: { _controller: OrthoBundle:Default:formulaireRecap }
    methods: [POST, GET]

