services:
#    ortho.example:
#        class: OrthoBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]

#    photos.example:
#        class: photosBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
