services:
    app.form.user.edit:
        class: OrthoBundle\Form\Type\EditProfileType
        tags:
            - { name: form.type, alias: app_user_edit }
        arguments:
            - %fos_user.model.user.class%