ortho_adj:
    resource: "@OrthoBundle/Resources/config/routing/adjonctions.yml"
    prefix:   /

ortho_app:
    resource: "@OrthoBundle/Resources/config/routing/appareillages.yml"
    prefix:   /

ortho_user:
    resource: "@OrthoBundle/Resources/config/routing/users.yml"
    prefix: /



ortho:
    resource: "@OrthoBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix:    /
