photos:
    resource: "@photosBundle/Resources/config/routing.yml"
    prefix:   /

ortho:
    resource: "@OrthoBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
