OrthoBundle\Entity\Commandes:
    properties:
        referencePatient:
            - NotBlank: BONJOUR

        dateretour:
            - NotBlank: ~

        fidApp:
            - NotBlank: ~

        fidAdj:
            - NotBlank: ~

        testimage:
            - Image: ~
