OrthoBundle\Entity\Commandes:
    properties:
        fidPatient:
            - NotBlank: ~

        dateretour:
            - NotBlank: ~

        fidApp:
            - NotBlank: ~

        fidAdj:
            - NotBlank: ~

        file:
            - Image: ~