uploads_index:
    path:     /
    defaults: { _controller: "photosBundle:Uploads:index" }
    methods:  GET

uploads_show:
    path:     /{id}/show
    defaults: { _controller: "photosBundle:Uploads:show" }
    methods:  GET

uploads_new:
    path:     /new
    defaults: { _controller: "photosBundle:Uploads:new" }
    methods:  [GET, POST]

uploads_edit:
    path:     /{id}/edit
    defaults: { _controller: "photosBundle:Uploads:edit" }
    methods:  [GET, POST]

uploads_create:
    path:     /create
    defaults: { _controller: "photosBundle:Uploads:create" }
    methods:  POST

uploads_delete:
    path:     /{id}/delete
    defaults: { _controller: "photosBundle:Uploads:delete" }
    methods:  DELETE
