<?php

namespace OrthoBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * LaboratoireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LaboratoireRepository extends EntityRepository
{
}
