<?php

namespace OrthoBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PoidsAppareillagesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PoidsAppareillagesRepository extends EntityRepository
{
}
