#/var/www/html/laloupe_orthodontics/src/photosBundle/Resources/config/routing.yml

photos_uploads:
    resource: "@photosBundle/Resources/config/routing/uploads.yml"
    prefix:   /uploads

photos_homepage:
    path:     /truc
    defaults: { _controller: photosBundle:Default:index }