OrthoBundle\Entity\Adjonctions:
    type: entity
    table: null
    repositoryClass: OrthoBundle\Repository\AdjonctionsRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        titreAdj:
            type: string
            length: 255
            column: titre_adj
        familleAdj:
            type: string
            length: 3
            column: famille_adj
        imgAdj:
            type: string
            length: 255
            nullable: true
            column: img_adj
        commentairesAdj:
            type: text
            column: commentaires_adj
        infoComLaboAdj:
            type: string
            length: 255
            column: info_com_labo_adj
            nullable: true
        infoComCabAdj:
            type: string
            length: 255
            column: info_com_cab_adj
            nullable: true

    manyToMany:
        fkidCommande:
            targetEntity: Commandes
            mappedBy: Adjonctions

    oneToMany:
        poids:
            targetEntity: OrthoBundle\Entity\PoidsAdjonctions
            mappedBy: fidAdjonction

    lifecycleCallbacks: {  }
