OrthoBundle\Entity\Adjonctions:
    type: entity
    table: null
    repositoryClass: OrthoBundle\Repository\AdjonctionsRepository
    id:
        idAdj:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        titreAdj:
            type: string
            length: 255
            column: titre_adj
        imgAdj:
            type: string
            length: 255
            nullable: true
            column: img_adj
        commentairesAdj:
            type: text
            column: commentaires_adj
        compteurAdj:
            type: integer
            nullable: false
            column: compteur_adj

    manyToMany:
        fkidCommande:
            targetEntity: Commandes
            mappedBy: Adjonctions

    lifecycleCallbacks: {  }
