OrthoBundle\Entity\AppAdjLabo:
    type: entity
    table: null
    repositoryClass: OrthoBundle\Repository\AppAdjLaboRepository
    id:
        idAppAdjLabo:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:

    manyToOne:
        fidApp:
            targetEntity: Appareillages
            joinColumn:
                name: fid_app
                referencedColumn: id
                nullable: false
                unique: false

        fidAdj:
            targetEntity: Adjonctions
            joinColumn:
                name: fid_adj
                referencedColumnName: id_adj
                nullable: false
                unique: false

        fidLabo:
            targetEntity: Laboratoire
            joinColumn:
                name: fid_labo
                referencedColumn: id
                nullable: false
                unique: false

    lifecycleCallbacks: {  }
