OrthoBundle\Entity\AppAdjLabo:
    type: entity
    table: app_adj_labo
    repositoryClass: OrthoBundle\Repository\AppAdjLaboRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO

    manyToOne:
        utilisateur:
            targetEntity: OrthoBundle\Entity\Utilisateurs
            inversedBy: boutonSpecifique

        appareillage:
            targetEntity: OrthoBundle\Entity\Appareillages
            inversedBy: boutonSpecifique

        adjonction:
            targetEntity: OrthoBundle\Entity\Adjonctions
            inversedBy: boutonSpecifique

    lifecycleCallbacks: {  }
