OrthoBundle\Entity\AppAdjLabo:
    type: entity
    table: null
    repositoryClass: OrthoBundle\Repository\AppAdjLaboRepository
    id:
        idAppAdjLabo:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:




    manyToOne:
        fidApp:
            targetEntity: Appareillages
            inversedBy: AppAdjLabo
            joinColumn:
                name: fid_app
                referencedColumnName: id_app
                nullable: false
                unique: false

        fidAdj:
            targetEntity: Adjonctions
            inversedBy: AppAdjLabo
            joinColumn:
                name: fid_adj
                referencedColumnName: id_adj
                nullable: false
                unique: false

        fidLabo:
            targetEntity: Laboratoire
            inversedBy: Commandes
            joinColumn:
                name: fid_labo
                referencedColumnName: id_labo
                nullable: false
                unique: false

    lifecycleCallbacks: {  }
