OrthoBundle\Entity\AppAdjLabo:
    type: entity
    table: null
    repositoryClass: OrthoBundle\Repository\AppAdjLaboRepository
    id:
        idAppAdjLabo:
            type: integer
            id: true
            generator:
                strategy: AUTO

    lifecycleCallbacks: {  }
