OrthoBundle\Entity\Appareillages:
    type: entity
    table: null
    repositoryClass: OrthoBundle\Repository\AppareillagesRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        titreApp:
            type: string
            length: 255
            column: titre_app
        familleApp:
            type: string
            length: 3
            column: famille_app
            nullable: false
        imgApp:
            type: string
            length: 255
            column: img_app
        commentairesApp:
            type: text
            column: commentaires_app
        infoComLaboApp:
            type: string
            length: 255
            column: info_com_labo_app
            nullable: true
        infoComCabApp:
            type: string
            length: 255
            column: info_com_cab_app
            nullable: true

    manyToMany:
        commandes:
            targetEntity: OrthoBundle\Entity\Commandes
            mappedBy: appareillages

        labos:
            targetEntity: OrthoBundle\Entity\Laboratoire
            mappedBy: appareillages

    oneToMany:
        poids:
            targetEntity: OrthoBundle\Entity\PoidsAppareillages
            mappedBy: fidAppareillages

    lifecycleCallbacks: {  }
