OrthoBundle\Entity\Cabinetsdentaires:
    type: entity
    table: null
    repositoryClass: OrthoBundle\Repository\CabinetsdentairesRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nomCab:
            type: string
            length: 255
            column: nom_cab
            nullable: true
        adresseCab:
            type: string
            length: 255
            column: adresse_cab
            nullable: true
        codepostalCab:
            type: string
            length: 255
            column: codepostal_cab
            nullable: true
        villeCab:
            type: string
            length: 255
            column: ville_cab
            nullable: true
        telephoneCab:
            type: string
            length: 255
            column: telephone_cab
            nullable: true


    lifecycleCallbacks: {  }
