OrthoBundle\Entity\Cabinetsdentaires:
    type: entity
    table: null
    repositoryClass: OrthoBundle\Repository\CabinetsdentairesRepository
    id:
        idCab:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nomCab:
            type: string
            length: 255
            column: nom_cab
        adresseCab:
            type: string
            length: 255
            column: adresse_cab
        codepostalCab:
            type: string
            length: 255
            column: codepostal_cab
        villeCab:
            type: string
            length: 255
            column: ville_cab
        email:
            type: string
            length: 255
            column: email
        telephoneCab:
            type: string
            length: 255
            column: telephone_cab
        username:
            type: string
            length: 255
            column: pseudo_cab
        password:
            type: string
            length: 255
            column: password_cab

    manyToOne:
            fidLabo:
                targetEntity: Laboratoire
                joinColumn:
                    name: fid_labo
                    referencedColumnName: id_labo
                    nullable: false


    lifecycleCallbacks: {  }
