OrthoBundle\Entity\Cabinetsdentaires:
    type: entity
    table: null
    repositoryClass: OrthoBundle\Repository\CabinetsdentairesRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nomCab:
            type: string
            length: 255
            column: nom_cab
            nullable: true
        adresseCab:
            type: string
            length: 255
            column: adresse_cab
            nullable: true
        codepostalCab:
            type: string
            length: 255
            column: codepostal_cab
            nullable: true
        villeCab:
            type: string
            length: 255
            column: ville_cab
            nullable: true
        telephoneCab:
            type: string
            length: 255
            column: telephone_cab
            nullable: true
        adressebisCab:
            type: string
            length: 255
            column: adressebis_cab
            nullable: true
        codepostalbisCab:
            type: string
            length: 255
            column: codepostalbis_cab
            nullable: true
        villebisCab:
            type: string
            length: 255
            column: villebis_cab
            nullable: true
        telephonebisCab:
            type: string
            length: 255
            column: telephonebis_cab
            nullable: true
        mailCab:
            type: string
            length: 255
            column: mail_cab
            nullable: true
        emailbisCab:
            type: string
            length: 255
            column: emailbis_cab
            nullable: true
        emailterCab:
            type: string
            length: 255
            column: emailter_cab
            nullable: true

    manyToOne:
        fidLabo:
            targetEntity: OrthoBundle\Entity\Laboratoire
            joinColumn:
                name: fid_labo
                referencedColumn: id
                nullable: true

    oneToMany:
        poids:
            targetEntity: OrthoBundle\Entity\PoidsAppareillages
            mappedBy: cabinet

        poidsAdjonction:
            targetEntity: OrthoBundle\Entity\PoidsAdjonctions
            mappedBy: cabinet

    lifecycleCallbacks: {  }
