OrthoBundle\Entity\Commandes:
    type: entity
    table: null
    repositoryClass: OrthoBundle\Repository\CommandesRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        referencePatient:
            type: string
            length: 255
        prenomPatient:
            type: string
            length: 255
            nullable: true
        dateRetour:
            type: date
        dateCommande:
            type: datetime
        commentaireLabo:
            type: text
        path1:
            type: string
            nullable: true
        path2:
            type: string
            nullable: true
        path3:
            type: string
            nullable: true
        commentairePrestataire3D:
            type: text

    manyToMany:
        appareillages:
            targetEntity: OrthoBundle\Entity\Appareillages
            joinTable:
                name: commandes_appareillages
                joinColumns:
                    commandes_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    appareillages_id:
                        referencedColumnName: id

        adjonctions:
            targetEntity: OrthoBundle\Entity\Adjonctions
            joinTable:
                name: commandes_adjonctions
                joinColumns:
                    commandes_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    adjonctions_id:
                        referencedColumnName: id

    manyToOne:
        utilisateur:
            targetEntity: OrthoBundle\Entity\Utilisateurs
            inversedBy: commandes

        couleur:
            targetEntity: OrthoBundle\Entity\Couleurs
            inversedBy: commande

        motif:
            targetEntity: OrthoBundle\Entity\Motifs
            inversedBy: commandes

    lifecycleCallbacks:
        prePersist: [ setCreatedAtValue ]
        postPersist: [ upload1 ]
        postUpdate: [ upload1 ]

