OrthoBundle\Entity\Commandes:
    type: entity
    table: null
    repositoryClass: OrthoBundle\Repository\CommandesRepository
    id:
        idCommande:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        fidLaboratoire:
            type: integer
            column: fid_laboratoire
        fidPatient:
            type: integer
            column: fid_patient
        fnomPatient:
            type: string
            length: 255
            column: fnom_patient
        dateretour:
            type: date
        datecommande:
            type: date
        fidApp:
            type: integer
            column: fid_app
        fidAdj:
            type: integer
            column: fid_adj

    manyToOne:
        fidCabinet:
            targetEntity: Cabinetsdentaires
            inversedBy: Commandes
            joinColumn:
                name: fid_cabinet
                referencedColumnName: id_cab
                nullable: false
    lifecycleCallbacks: {  }
