OrthoBundle\Entity\Commandes:
    type: entity
    table: null
    repositoryClass: OrthoBundle\Repository\CommandesRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO


    fields:
        referencePatient:
            type: string
            length: 125
            column: reference_patient
        prenomPatient:
            type: string
            length: 125
            column: prenom_patient
        dateretour:
            type: date
        datecommande:
            type: datetime
        comment:
            type: text
            nullable: true
        ajoutApp:
            type: text
            nullable: true
        comment2:
            type: text
            nullable: true
        path1:
            type: string
            length: 245
            nullable: true
        path2:
            type: string
            nullable: true
        path3:
            type: string
            nullable: true


    manyToOne:
        fidCabinet:
            targetEntity: Cabinetsdentaires
            joinColumn:
                name: fid_cabinet
                referencedColumn: id
                nullable: true

        fidLaboratoire:
            targetEntity: Laboratoire
            joinColumn:
                name: fid_laboratoire
                referencedColumn: id
                nullable: true

        fidCouleur:
            targetEntity: OrthoBundle\Entity\Couleur
            joinColumn:
                name: fid_couleur
                referencedColumnName: id_couleur
                nullable: false

        fidMotif:
            targetEntity: OrthoBundle\Entity\Motif
            joinColumn:
                name: fid_motif
                referencedColumnName: id_motif
                nullable: false


    manyToMany:
         appareillages:
             targetEntity: Appareillages
             inversedBy: commandes

         fidAdj:
             targetEntity: Adjonctions
             inversedBy: Commandes
             joinTable:
                 name: Commandes_Adjonctions
                 joinColumns:
                     Commandes_id:
                         referencedColumn: id
                 inverseJoinColumns:
                     Adjonctions_id:
                         referencedColumn: id


    lifecycleCallbacks:
        prePersist: [ setCreatedAtValue ]
        postPersist: [ upload1, upload2, upload3 ]
        postUpdate: [ upload1, upload2, upload3 ]
