OrthoBundle\Entity\Commandes:
    type: entity
    table: null
    repositoryClass: OrthoBundle\Repository\CommandesRepository
    id:
        idCommande:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:

        referencePatient:
            type: string
            length: 125
            column: reference_patient
        prenomPatient:
            type: string
            length: 125
            column: prenom_patient
        dateretour:
            type: date
        datecommande:
            type: datetime

    manyToOne:
        fidCabinet:
            targetEntity: Cabinetsdentaires
            joinColumn:
                name: fid_cabinet
                referencedColumnName: id_cab
                nullable: true

        fidLaboratoire:
            targetEntity: Laboratoire
            joinColumn:
                name: fid_laboratoire
                referencedColumnName: id_labo
                nullable: true

        fidCouleur:
            targetEntity: OrthoBundle\Entity\Couleur
            joinColumn:
                name: fid_couleur
                referencedColumnName: id_couleur
                nullable: false

        fidMotif:
            targetEntity: OrthoBundle\Entity\Motif
            joinColumn:
                name: fid_motif
                referencedColumnName: id_motif
                nullable: false

    manyToMany:
         fidApp:
             targetEntity: Appareillages
             inversedBy: Commandes
             joinTable:
                 name: Commandes_Appareillages
                 joinColumns:
                     Commandes_id:
                         referencedColumnName: id_commande
                 inverseJoinColumns:
                     Appareillages_id:
                         referencedColumnName: id_app

         fidAdj:
             targetEntity: Adjonctions
             inversedBy: Commandes
             joinTable:
                 name: Commandes_Adjonctions
                 joinColumns:
                     Commandes_id:
                         referencedColumnName: id_commande
                 inverseJoinColumns:
                     Adjonctions_id:
                         referencedColumnName: id_adj

    lifecycleCallbacks:
          prePersist: [setCreatedAtValue]
