OrthoBundle\Entity\Couleur:
    type: entity
    table: null
    repositoryClass: OrthoBundle\Repository\CouleurRepository
    id:
        idCouleur:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nomCouleur:
            type: string
            length: 255
            column: nom_couleur
    lifecycleCallbacks: {  }
