OrthoBundle\Entity\Listepatients:
    type: entity
    table: null
    repositoryClass: OrthoBundle\Repository\ListepatientsRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        datenaissancePatient:
            type: string
            length: 255
            column: datenaissance_patient
        nomPatient:
            type: string
            length: 255
            column: nom_patient
        prenomPatient:
            type: string
            length: 255
            column: prenom_patient

    manyToOne:
        fidCab:
            targetEntity: Cabinetsdentaires
            inversedBy: Listepatients
            joinColumn:
                name: fid_cab
                referencedColumn: id
                nullable: false
    lifecycleCallbacks: {  }
