OrthoBundle\Entity\Motif:
    type: entity
    table: null
    repositoryClass: OrthoBundle\Repository\MotifRepository
    id:
        idMotif:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nomMotif:
            type: string
            length: 255
            column: nom_motif
    lifecycleCallbacks: {  }
