OrthoBundle\Entity\PoidsAdjonctions:
    type: entity
    table: null
    repositoryClass: OrthoBundle\Repository\PoidsAdjonctionsRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        poids:
            type: integer

    lifecycleCallbacks: {  }
