OrthoBundle\Entity\PoidsAppareillages:
    type: entity
    table: poids_appareillages
    repositoryClass: OrthoBundle\Repository\PoidsAppareillagesRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        poids:
            type: integer

    manyToOne:
        appareillage:
            targetEntity: OrthoBundle\Entity\Appareillages
            inversedBy: poidsApp

        utilisateur:
            targetEntity: OrthoBundle\Entity\Utilisateurs
            inversedBy: poidsApp



    lifecycleCallbacks: {  }

