OrthoBundle\Entity\PoidsAdjonctions:
    type: entity
    table: poids_adjonctions
    repositoryClass: OrthoBundle\Repository\PoidsAdjonctionsRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        poids:
            type: integer

    manyToOne:
        adjonction:
            targetEntity: OrthoBundle\Entity\Adjonctions
            inversedBy: poids

        utilisateur:
            targetEntity: OrthoBundle\Entity\Utilisateurs
            inversedBy: poidsAdj




    lifecycleCallbacks: {}
