OrthoBundle\Entity\Utilisateurs:
    type: entity
    table: null
    repositoryClass: OrthoBundle\Repository\UtilisateursRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nom:
            type: string
            length: 255
        adresse:
            type: string
            length: 255
        codePostal:
            type: string
            length: '5'
        ville:
            type: string
            length: 255
        telephone:
            type: string
            length: 255

    manyToOne:
        categorie:
            targetEntity: OrthoBundle\Entity\CategorieUtilisateurs
            inversedBy: utilisateur
            joinColumn:
                nullable: false

        labo:
            targetEntity: OrthoBundle\Entity\Utilisateurs
            inversedBy: id
            joinColumn:
                nullable: true

    oneToMany:
        poidsAdj:
            targetEntity: OrthoBundle\Entity\PoidsAdjonctions
            mappedBy: utilisateur

        poidsApp:
            targetEntity: OrthoBundle\Entity\PoidsAppareillages
            mappedBy: utilisateur

        boutonSpecifique:
            targetEntity: OrthoBundle\Entity\AppAdjLabo
            mappedBy: utilisateur

        commandes:
            targetEntity: OrthoBundle\Entity\Commandes
            mappedBy: utilisateur

    lifecycleCallbacks: {  }
