INSERT INTO appareillages (titre_app, img_app, commentaires_app, compteur_app, famille_app, info_com_labo_app, info_com_cab_app) VALUES
('Arc Lingual', 'http://www.neo3d.fr/imgbase/fix/0000fix0001.jpg', 'Réaliser un Arc lingual soudé s/ bagues', 0, 'fix', 'Fil 0.9 à -20% chez dentaurum', 'Nouvelles bagues RMO slim'),
('Arc de Nance', 'http://www.neo3d.fr/imgbase/fix/0000fix0002.jpg', 'Réaliser un Arc de Nance soudé s/ bagues', 0, 'fix', 'Fil 0.9 à -20% chez dentaurum', 'Nouvelles bagues RMO slim'),
('Arc Palatin', 'http://www.neo3d.fr/imgbase/fix/0000fix0003.jpg', 'Réaliser un Arc Palatin soudé s/ bagues', 0, 'fix', 'Fil 0.9 à -20% chez dentaurum', 'Nouvelles bagues RMO slim'),
('Arc Transpalatin', 'http://www.neo3d.fr/imgbase/fix/0000fix0004.jpg', 'Réaliser un Arc Transpalatin soudé s/ bagues', 0, 'fix', 'Fil 0.9 à -20% chez dentaurum', 'Nouvelles bagues RMO slim'),
('Arc NTP', 'http://www.neo3d.fr/imgbase/fix/0000fix0005.jpg', 'Réaliser un Arc NTP soudé s/ bagues', 0, 'fix', 'Fil 0.9 à -20% chez dentaurum', 'Nouvelles bagues RMO slim'),
('Arc Lingual idéal', 'http://www.neo3d.fr/imgbase/fix/0000fix0006.jpg', 'Réaliser un Arc Lingual idéal soudé s/ bagues', 0, 'fix', 'Fil 0.9 à -20% chez dentaurum', 'Nouvelles bagues RMO slim'),
('Arc Double de delaire', 'http://www.neo3d.fr/imgbase/fix/0000fix0007.jpg', 'Réaliser un Arc Double de delaire soudé', 0, 'fix', 'Fil 0.9 à -20% chez dentaurum', 'Nouvelles bagues RMO slim'),
('Quad Hélix', 'http://www.neo3d.fr/imgbase/fix/0000fix0002.jpg', 'Réaliser un QH soudé s/ bagues', 0, 'fix', 'Fil 0.9 à -20% chez dentaurum', 'Nouvelles bagues RMO slim'),
('Plaque Palatine', 'http://www.neo3d.fr/imgbase/mob/0000mob0001.jpg', 'Réaliser un Plaque Palatine', 0, 'mob', 'Nouvelle résine chez LaboShop !', NULL),
('Plaque de Hawley', 'http://www.neo3d.fr/imgbase/mob/0000mob0002.jpg', 'Réaliser une Plaque de Hawley', 0, 'mob', 'Nouvelle résine chez LaboShop !', NULL),
('Gouttière de contention', 'http://www.neo3d.fr/imgbase/mob/0000mob0003.jpg', 'Réaliser une Gouttière de contention', 0, 'mob', 'Nouvelle résine chez LaboShop !', NULL),
('Plaque mandibulaire', 'http://www.neo3d.fr/imgbase/mob/0000mob0004.jpg', 'Réaliser une Plaque mandibulaire', 0, 'mob', 'Nouvelle résine chez LaboShop !', NULL),
('Monobloc Lautrou', 'http://www.neo3d.fr/imgbase/mob/0000mob0005.jpg', 'Réaliser un Monobloc de Lautrou', 0, 'mob', 'Nouvelle résine chez LaboShop !', NULL),
('Monobloc Chabre', 'http://www.neo3d.fr/imgbase/mob/0000mob0006.jpg', 'Réaliser un Monobloc de Chabre', 0, 'mob', 'Nouvelle résine chez LaboShop !', NULL),
('Bielle de Herbst', 'http://www.neo3d.fr/imgbase/mob/0000mob0007.jpg', 'Réaliser une Bielle de Herbst', 0, 'mob', 'Nouvelle résine chez LaboShop !', NULL),
('Bielle de Tavernier', 'http://www.neo3d.fr/imgbase/mob/0000mob0008.jpg', 'Réaliser une Bielle de Tavernier', 0, 'mob', 'Nouvelle résine chez LaboShop !', NULL),
('PUL 1', 'http://www.neo3d.fr/imgbase/mob/0000mob0009.jpg', 'Réaliser un PUL 1', 0, 'mob', "PUL à -15% dispo jusqu'au 30 Juin", 'Formation PUL ! Places disponible !'),
('PUL 2', 'http://www.neo3d.fr/imgbase/mob/0000mob00010.jpg', 'Réaliser un PUL 1', 0, 'mob', "PUL à -15% dispo jusqu'au 30 Juin", 'Formation PUL ! Places disponible !'),
('Impression Moulage mini', 'http://www.neo3d.fr/imgbase/met/0000met0001.jpg', 'Imprimer le moulage au plus court', 0, 'met', 'Nouvelle résine chez LaboShop !', NULL),
("Impression Moulage d'étude", 'http://www.neo3d.fr/imgbase/met/0000met0002.jpg', "Imprimer le moulage d'étude", 0, 'met', 'Nouvelle résine chez LaboShop !', NULL),
("Moulage d'étude 3D", 'http://www.neo3d.fr/imgbase/met/0000met0003.jpg', "Réaliser un moulage virtuel", 0, 'met', 'Nouvelle résine chez LaboShop !', NULL);