<?php

namespace photosBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UploadsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UploadsRepository extends EntityRepository
{
}
